# Site settings
title: Example Title
email: example@email.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Peter Forward
email: petejenny@hotmail.com
facebook_username: pgforward
twitter_username: @OzBlend
github_username: pgforward
address:
  - line: Address Line One
  - line: Address Line Two
  # Feel free to add more lines here 
telephone:
copyright: (c) 2020

# API settings
google_api_key:

# Build settings
markdown: kramdown
